### ISSUE TITLE
Support for Python 3.1/3.2

### ISSUE THREAD

**Issue by essobi** [psypanda/hashID#28]
File "./hashID/hashid.py", line 177
    HashInfo(name=u'Wordpress ≥ v2.6.2', hashcat=400, john='phpass', extended=False),
                                        ^
SyntaxError: invalid syntax

**Comment by psypanda** [comment]
This happens because the python version in the current Kali Linux (v1.1.0) is **v3.2.3** which [does not support Python 2's Unicode literal syntax](https://www.python.org/dev/peps/pep-0414/).

For now I'll make it more obvious which Python versions hashID is compatible with.
I'll leave this open until Kali is based on Debian Jessie which uses Python 3.4

**Comment by 0x90shell** [comment]
Yes, I noticed the syntax issues in Jan and just altered to:

#!/usr/bin/env python2.7

Haven't noticed any issues with the quick fix.

**Comment by psypanda** [comment]
Since 2c3973ba332980ae3749c82ca9ce95a6f37031b6 hashID should be fully compatible with python2.7 - No need to edit the shebang anymore

**Comment by essobi** [comment]
Smexy... Thanks..
